---
output: github_document
---

# Test
```{r}

dur_hablo_stressed <- 0.52486

dur_hablo_unstressed <-0.52557

dur_o_stressed <-0.24278

dur_o_unstressed <- 0.24191 

int_o_stressed <-75.32110

int_o_unstressed <-72.48682

f0_o_stressed <- 231.13417

f0_o_unstressed <-258.24542

```

# Duration Differences

```{r}
# The difference in ms between “hablo” and “habló”
dur_hablo_stressed - dur_hablo_unstressed

#The difference in ms between the stressed and unstressed [o]
dur_o_stressed - dur_o_unstressed

#The difference in intensity between the stressed and unstressed [o]
int_o_stressed - int_o_unstressed

#The difference in F0 between the stressed and unstressed [o]
f0_o_stressed - f0_o_unstressed

```



# Observations 
The stressed and unstressed forms of hablo/habló show only minimal differences in overall word and vowel duration (less than 1 ms). However, the stressed [o] is noticeably louder, with about 2.8 dB more intensity, while its pitch is about 27 Hz lower than the unstressed [o].

